### PR TITLE
Prefix only ignore_keys that are not defined

### PR DESCRIPTION
**Pull request by grappler**
If I define my own ignore key I don't really want it to be prefixed or shortened. It is fine to do so if the generated key is like that.

### CODE REVIEW

**Comment by Shelob9** [comment]
The reason I prefix all of them is so they can be reliably searched for (and deleted) using a LIKE comparison on the meta_key column. It's a feature I meant to add.

**Comment by grappler** [comment]
If you define your own key then you could prefix it then with your version but this would allow others to have their own non prefixed version.

**Comment by Shelob9** [comment]
Fair enough.

**Comment by Shelob9** [comment]
Ok, I buy that.

**Pull request merged**
