### PR TITLE
Correct the default capability to manage_options

### PR DESCRIPTION
**Pull request by grappler**

### CODE REVIEW

**Comment by grappler** [comment]
@Shelob9 Any reason why you did not merge this?

**Comment by Shelob9** [comment]
Because I meant to say, "shouldn't it be activate_plugins?"

**Comment by grappler** [comment]
It depends what the message is for? The message that I am adding is that I am deprecating one of the filters in my plugin. I don't mind what the default should be. The previous cap was "update_options" which is not a valid capability.

**Comment by Shelob9** [comment]
@grappler Right, the existing default was wrong, but I'm just saying, if someone has the ability to activate plugins, which may be someone of less than admin with custom caps, then they should see the warning. That seems like a sensible default that you can overide in your usage.

**Comment by grappler** [comment]
Makes sense. I have updated the PR.

**Pull request merged**
